services:
  web:
    build:
      context: .
      dockerfile: docker/docker-django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - action: sync
          path: ./eLearningApp
          target: ./eLearningApp
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: docker/docker-django/Dockerfile
    command: celery --app=uolAwdFinal.celery:app worker --loglevel=info --pidfile=celery.pid
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: uolAwdFinal.settings
