services:
  web:
    build:
      context: .
      dockerfile: docker/docker-django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - action: sync
          path: ./eLearningApp
          target: ./eLearningApp
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"