# Generated by Django 4.2.14 on 2024-08-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0004_alter_course_lecturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("deadline", models.DateField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eLearningApp.course",
                    ),
                ),
            ],
        ),
    ]
