# Generated by Django 4.2.14 on 2024-08-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eLearningApp", "0012_file_author_file_institution_file_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eLearningApp.institution",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
