# Generated by Django 4.2.14 on 2024-08-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eLearningApp", "0013_alter_file_author_alter_file_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eLearningApp.course",
            ),
        ),
    ]
